// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhwnxgjdyahdkdjfeuhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxod254Z2pkeWFoZGtkamZldWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzY3MDgsImV4cCI6MjA2OTkxMjcwOH0.7tthswWl99ZLFyIXI5yKqENc7SoLDVJAPWjjVbfjbhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});